// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQYnrodsIGcqTfSmy8ZGYyhGfmXj79Zw',
    appId: '1:804047585830:web:cb4f8d89306eda63e7dce7',
    messagingSenderId: '804047585830',
    projectId: 'quize-app-de07c',
    authDomain: 'quize-app-de07c.firebaseapp.com',
    storageBucket: 'quize-app-de07c.appspot.com',
    measurementId: 'G-2BM673W7XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8h1UqntV4IJg6P5s4KF4EKf7Nl1RhdZ8',
    appId: '1:804047585830:android:540446b7b61b9920e7dce7',
    messagingSenderId: '804047585830',
    projectId: 'quize-app-de07c',
    storageBucket: 'quize-app-de07c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRf0p355IUVar0hi70TEOUkytR4o678BA',
    appId: '1:804047585830:ios:72eea377b27a8f22e7dce7',
    messagingSenderId: '804047585830',
    projectId: 'quize-app-de07c',
    storageBucket: 'quize-app-de07c.appspot.com',
    iosClientId: '804047585830-evn8kci2lfnohl5k94a019piqn9pvrsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizeApp',
  );
}
